<a href="https://colab.research.google.com/github/KeisukeShimokawa/CarND-Advanced-Lane-Lines/blob/master/ml/applied-deep-learning-build-a-chatbot/comp_chatbot_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Section24 Transformers

### 24.1 introduction to Transformers

![](https://i.gyazo.com/d5c131c855acf22d406c4604aa4e3ffc.png)

![](https://i.gyazo.com/26640d0bac11c490b1428ed10db64f37.png)

RNNは近距離をより重視

![](https://i.gyazo.com/e1758b31a94e3bdfdddf124f175e98f9.png)

Attentionの長所

![](https://i.gyazo.com/142a9206eb9e0b549b320910589d69af.png)

複数の個所を向くそれぞれのヘッドを用意

![](https://i.gyazo.com/901330f92f21ff5928320f5743b33127.png)

### 24.2 input Embeddings

![](https://i.gyazo.com/77a8fc18ae65a262ecd79f6ee5c83db1.png)

従来はPaddingを行っている。

![](https://i.gyazo.com/926839648f9a9f41307fec24e4a2fb3d.png)

各単語に対応するWord Embeddingに変換する。

![](https://i.gyazo.com/94a5da007b1a692295f46ca4023cedeb.png)

![](https://i.gyazo.com/ae094c9f95f20df8ce38e4d9799a9aba.png)

### 24.3 Positional Encoding

Tranformersでは、時系列に沿ってデータを与えないため、各単語のどの位置で出現したのかその情報を計算する必要がある。

![](https://i.gyazo.com/a5e8f5d0b584e41415d7037bcdedb15c.png)

着想は三角関数の対応

![](https://i.gyazo.com/f8215862a86280cdd1907ffda5ed52a5.png)

![](https://i.gyazo.com/06ceed86be162fae36087fddcf5847a2.png)

Word Embedding似合わせた次元数を指定する。

![](https://i.gyazo.com/602c1bb32c600b26fd786a1b6f9215ad.png)


![](https://i.gyazo.com/53ed598fb17f4d8f5d6ff3bf8efe5c03.png)


![](https://i.gyazo.com/ac64c07add3a3786213b8eac634aa94d.png)


![](https://i.gyazo.com/834e30540454a0458baee41b7464a67c.png)

WordベクトルとPositional Encodingを使用して最終的にTransformerに入力するデータを生成します。しかしWordベクトルのほうが意味の情報を有しているため、単語ベクトルにはより重みを付けて意味がなくなってしまわないように計算を行っています。

![](https://i.gyazo.com/ca08d9760ed6d7c86bf02b2c58ae4eae.png)

![](https://i.gyazo.com/d72693ea3cf936681dd81651f3a0ee9d.png)

#### 参考情報

- [What is the positional encoding in the transformer model?](https://datascience.stackexchange.com/questions/51065/what-is-the-positional-encoding-in-the-transformer-model)
- [Transformer Architecture: The Positional Encoding](https://kazemnejad.com/blog/transformer_architecture_positional_encoding/)
- [reddit positional encoding](https://www.reddit.com/r/learnmachinelearning/comments/a35goa/positional_encoding/)
- [experiment positional encoding](https://github.com/kaushalshetty/Positional-Encoding)

### 24.4 MultiHead Attention


![](https://i.gyazo.com/3793d7236497a677ef52a830e0ae3b2d.png)

複数の線型結合層を使用して、それぞれ異なる注意機構として動作させる。互いに異なる部分に注意付きを行っている。

![](https://i.gyazo.com/a90384e80f62e5d71a04d573d3ed318b.png)



![](https://i.gyazo.com/146ee5b73ace7aa7036fd5b3a143cf96.png)

まずは同一の入力となる単語ベクトルに対して、線型結合層を適用してベクトルの次元を変換します。この際に、使用するヘッドの数に応じて、投影先のベクトルの次元を決定する。

![](https://i.gyazo.com/0a5aab6a54f8e0f96adae4b6e9970577.png)



![](https://i.gyazo.com/48678fb4428e06e672bffc251bd890a1.png)

![](https://i.gyazo.com/c8a5d702ce8f39152dd65aa6b0d9ddec.png)

![](https://i.gyazo.com/75f42e96978b741ec6a56200c387d5cb.png)

![](https://i.gyazo.com/1456581356ea7cc8bde77e5c82035062.png)

![](https://i.gyazo.com/17f4c46a36398bab61c85a4068b718c4.png)

Dot積ではなく要素積でも計算可能。

![](https://i.gyazo.com/1bc5d86fe59c1f88e3e523093f6a0ee3.png)

### 24.5 Concat and Linear



![](https://i.gyazo.com/557a99b416c0972f285a5d0ab360bf9d.png)


![](https://i.gyazo.com/ac2bb39244bb1a7a833dd58382bc669e.png)

### 24.6 Residual Learning

![](https://i.gyazo.com/b631778efc8b17691f52366a3771ed70.png)

![](https://i.gyazo.com/ddaff51f2446c75480046228ea2f171d.png)

![](https://i.gyazo.com/a4cfe4761d4229b787defc0095939502.png)

### 24.7 Layer Normalization

![](https://i.gyazo.com/56889d251ca17948001e1a22d7a8a24e.png)

![](https://i.gyazo.com/70c8f656d1c2c3117d26f2c54e0f9d90.png)

![](https://i.gyazo.com/8b03300ce20a34bde1341c70659493ec.png)

- [Batch Normalizationとその派生の整理
2019/6/16](https://gangango.com/2019/06/16/post-573/)

### 24.8 Feed Forward

![](https://i.gyazo.com/2539ff7c359dca69d4aac997b87d9f04.png)

![](https://i.gyazo.com/b71fad6de216e4ed95cb38d3915c6a47.png)

![](https://i.gyazo.com/a2f9ccc57ca934e170b06057ab0342af.png)

### 24.9 Masked MultiHead Attention

![](https://i.gyazo.com/051ac0120060a9e5d86869bfae35d45d.png)


![](https://i.gyazo.com/49d2cfaa935853bf425397fdb956a81c.png) ![](https://i.gyazo.com/d4af70f2b17698907c80ae6d3144089e.png) ![](https://i.gyazo.com/fcef7a80df21956a806091b5c01b01bf.png)

![](https://i.gyazo.com/97314f961082b247c001163c6f21b0de.png)

![](https://i.gyazo.com/edecb40f209f3a5dd2531e1fcb78814a.png)

### 24.10 MultiHead Attention in Decoder

![](https://i.gyazo.com/cc272c0776dd50f76228897e97fd158e.png)

### 24.11 Cross Entropy Loss

![](https://i.gyazo.com/04a196a1687f56385652c6a641b9f237.png)

![](https://i.gyazo.com/104f959c855c275fa5f21936f017aa43.png)

![](https://i.gyazo.com/7dc03051c8f0dd3295c65a575c175808.png)

![](https://i.gyazo.com/61b53e5c78da2d01703ac0152755f116.png)

![](https://i.gyazo.com/90c2cb2f4612315d8b82dd144ba9b0ae.png)

![](https://i.gyazo.com/688913adc294bc6dfdc5f9476f4c2282.png)

![](https://i.gyazo.com/521f6f754467c63422144e2eb40956ff.png)


### 24.12 KL Divergence Loss

![](https://i.gyazo.com/6b735895c8de08760f4a8e3f904458ab.png)

![](https://i.gyazo.com/6d8eb084bac346966000a808443efdc9.png)

![](https://i.gyazo.com/c6529dda9affdd223dca12c1523ea874.png)

![](https://i.gyazo.com/360a18a93b2205b9ebd1487abdcba8e2.png)

![](https://i.gyazo.com/0e2092bc0085771a119984d9392a16ee.png)

### 24.13 Label Smoothing

![](https://i.gyazo.com/1657a804a3e6430b8e67547ab93e8547.png)

![](https://i.gyazo.com/8bb2a98fce9bbd3253001b62e1a07f31.png)

![](https://i.gyazo.com/bd809bd372e284c1ebdceae27c104330.png)



### 24.14 Dropout

![](https://i.gyazo.com/105690da3223dc0c8e502a242feeb1ee.png)

![](https://i.gyazo.com/757a1b659d09e05783f072f1538d5dec.png)

![](https://i.gyazo.com/6fce9f437eab11f3111662e4b0094f8e.png)

![](https://i.gyazo.com/bf30ec53b6e249ee17151a6906debbf1.png)

![](https://i.gyazo.com/070fe28b0e3158abc5a017708a6dcacd.png)

![](https://i.gyazo.com/cce90c51e225a81b475fab14ea550293.png)

### 24.15 Learning Rate WarmUp

![](https://i.gyazo.com/87702a8fb856978713a6573fe5eee7c3.png)

![](https://i.gyazo.com/9a581219e2424688bc80a8e8904ac958.png)

## Section25 Chatbot

[code](https://github.com/fawazsammani/chatbot-transformer)

### 25.1 Dataset Preparation

In [1]:
!wget http://www.cs.cornell.edu/~cristian/data/cornell_movie_dialogs_corpus.zip -O cornell_movie_dialogs_corpus.zip
!unzip -q -o cornell_movie_dialogs_corpus.zip
!ls

--2020-03-14 08:04:39--  http://www.cs.cornell.edu/~cristian/data/cornell_movie_dialogs_corpus.zip
Resolving www.cs.cornell.edu (www.cs.cornell.edu)... 132.236.207.20
Connecting to www.cs.cornell.edu (www.cs.cornell.edu)|132.236.207.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9916637 (9.5M) [application/zip]
Saving to: ‘cornell_movie_dialogs_corpus.zip’

cornell_movie_dialo 100%[===================>]   9.46M  2.61MB/s    in 4.1s    

2020-03-14 08:04:44 (2.31 MB/s) - ‘cornell_movie_dialogs_corpus.zip’ saved [9916637/9916637]

'cornell movie-dialogs corpus'	    __MACOSX
 cornell_movie_dialogs_corpus.zip   sample_data


In [0]:
from collections import Counter
import json
import torch
import torch.nn as nn
import torch.utils.data
from torch.utils.data import Dataset
import math
import torch.nn.functional as F

In [3]:
print(torch.__version__)

1.4.0


In [0]:
corpus_movie_conv  = "cornell movie-dialogs corpus/movie_conversations.txt"
corpus_movie_lines = "cornell movie-dialogs corpus/movie_lines.txt"
max_len = 25

In [0]:
with open(corpus_movie_conv, encoding='utf-8', errors='ignore') as c:
    conv = c.read().split('\n')

with open(corpus_movie_lines, encoding='utf-8', errors='ignore') as l:
    lines = l.read().split('\n')

In [6]:
conv[:3]

["u0 +++$+++ u2 +++$+++ m0 +++$+++ ['L194', 'L195', 'L196', 'L197']",
 "u0 +++$+++ u2 +++$+++ m0 +++$+++ ['L198', 'L199']",
 "u0 +++$+++ u2 +++$+++ m0 +++$+++ ['L200', 'L201', 'L202', 'L203']"]

In [7]:
lines[:3]

['L1045 +++$+++ u0 +++$+++ m0 +++$+++ BIANCA +++$+++ They do not!',
 'L1044 +++$+++ u2 +++$+++ m0 +++$+++ CAMERON +++$+++ They do to!',
 'L985 +++$+++ u0 +++$+++ m0 +++$+++ BIANCA +++$+++ I hope so.']

In [9]:
type(conv[0].split(' +++$+++ ')[-1])

str

### 25.2 Create Line Dist

In [0]:
lines_dict = {}
for line in lines:
    opjects = line.split(' +++$+++ ')
    lines_dict[opjects[0]] = opjects[-1]

In [11]:
lines_dict['L1045']

'They do not!'

In [0]:
def remove_punc(string):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%~&*_~'''
    no_punc = ""
    for char in string:
        if char not in punctuations:
            no_punc = no_punc + char
    return no_punc.lower()

In [13]:
s = ""
s = s + "g"
print(s)
s = s + "u"
print(s)

g
gu


In [14]:
remove_punc("tgyusj!(@)ihdys")

'tgyusjihdys'

### 25.3 Create Q&A Pair Set

In [25]:
conv[0].split(' +++$+++ ')[-1]

"['L194', 'L195', 'L196', 'L197']"

In [26]:
eval(conv[0].split(' +++$+++ ')[-1])

['L194', 'L195', 'L196', 'L197']

In [16]:
lines_dict['L194']

'Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.'

In [17]:
lines_dict['L194'].strip().split()[:max_len]

['Can',
 'we',
 'make',
 'this',
 'quick?',
 'Roxanne',
 'Korrine',
 'and',
 'Andrew',
 'Barrett',
 'are',
 'having',
 'an',
 'incredibly',
 'horrendous',
 'public',
 'break-',
 'up',
 'on',
 'the',
 'quad.',
 'Again.']

In [0]:
pairs = []
for con in conv:

    if con == '':
        continue

    ids = eval(con.split(' +++$+++ ')[-1])
    for i in range(len(ids)):
        qa_pairs = []

        if i == len(ids) - 1:
          break

        first = remove_punc(lines_dict[ids[i]].strip())
        second = remove_punc(lines_dict[ids[i+1]].strip())
        qa_pairs.append(first.split()[:max_len])
        qa_pairs.append(second.split()[:max_len])

        pairs.append(qa_pairs)

In [48]:
pairs[0]

[['can',
  'we',
  'make',
  'this',
  'quick',
  'roxanne',
  'korrine',
  'and',
  'andrew',
  'barrett',
  'are',
  'having',
  'an',
  'incredibly',
  'horrendous',
  'public',
  'break',
  'up',
  'on',
  'the',
  'quad',
  'again'],
 ['well',
  'i',
  'thought',
  'wed',
  'start',
  'with',
  'pronunciation',
  'if',
  'thats',
  'okay',
  'with',
  'you']]

### 25.4 Create Word ID

In [0]:
word_freq = Counter()
for pair in pairs:
    word_freq.update(pair[0])
    word_freq.update(pair[1])

In [0]:
min_word_freq = 5
words = [ w for w in word_freq.keys() if word_freq[w] > min_word_freq]

In [63]:
for i, word in enumerate(words):
    print(i)
    print(word)
    if i == 5:
        break

0
can
1
we
2
make
3
this
4
quick
5
and


In [0]:
# first word index starts at 1
word_map = {k: v + 1 for v, k in enumerate(words)}
word_map['<unk>'] = len(word_map) + 1
word_map['<start>'] = len(word_map) + 1
word_map['<end>'] = len(word_map) + 1
word_map['<pad>'] = 0

In [66]:
word_map['can']

1

In [67]:
print('Total words are {}'.format(len(word_map)))

Total words are 18190


In [0]:
with open('WORDMAP_CORPUS.json', 'w') as f:
    json.dump(word_map, f)

In [70]:
!ls | grep WORDMAP

WORDMAP_CORPUS.json


### 25.5 Create Encoding Sentence Function for Q&A

In [0]:
def encode_question(words, word_map):
    enc_c = [word_map.get(word, word_map['<unk>']) for word in words] + \
            [word_map['<pad>']] * (max_len - len(words))

    return enc_c

In [0]:
def encode_reply(words, word_map):
    enc_c = [word_map['<start>']] + \
            [word_map.get(word, word_map['<unk>']) for word in words] + \
            [word_map['<end>']] + \
            [word_map['<pad>']] * (max_len - len(words))

    return enc_c

In [74]:
pairs[0][0]

['can',
 'we',
 'make',
 'this',
 'quick',
 'roxanne',
 'korrine',
 'and',
 'andrew',
 'barrett',
 'are',
 'having',
 'an',
 'incredibly',
 'horrendous',
 'public',
 'break',
 'up',
 'on',
 'the',
 'quad',
 'again']

In [75]:
encode_question(pairs[0][0], word_map)

[1,
 2,
 3,
 4,
 5,
 18187,
 18187,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 18187,
 13,
 14,
 15,
 16,
 17,
 18187,
 18,
 0,
 0,
 0]

### 25.6 Create FUnction for Neural Network

In [0]:
pairs_encoded = []
for pair in pairs:
    ques = encode_question(pair[0], word_map)
    ans = encode_reply(pair[1], word_map)

    pairs_encoded.append([ques, ans])

In [77]:
pairs_encoded[0]

[[1,
  2,
  3,
  4,
  5,
  18187,
  18187,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  18187,
  13,
  14,
  15,
  16,
  17,
  18187,
  18,
  0,
  0,
  0],
 [18188,
  19,
  20,
  21,
  22,
  23,
  24,
  18187,
  25,
  26,
  27,
  24,
  28,
  18189,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]]

In [0]:
with open('pairs_encoded.json', 'w') as f:
    json.dump(pairs_encoded, f)

In [79]:
!ls

'cornell movie-dialogs corpus'	    __MACOSX		 sample_data
 cornell_movie_dialogs_corpus.zip   pairs_encoded.json	 WORDMAP_CORPUS.json


In [0]:
class Dataset(Dataset):
    def __init__(self, path='pairs_encoded.json'):
        self.pairs = json.load(open(path))
        self.dataset_size = len(self.pairs)

    def __getitem__(self, i):
        question = torch.LongTensor(self.pairs[i][0])
        reply = torch.LongTensor(self.pairs[i][1])

        return question, reply

    def __len__(self):
        return self.dataset_size

### 25.7 Data Loading and Masking

In [0]:
train_loader = torch.utils.data.DataLoader(Dataset(), 
                                           batch_size=100, 
                                           shuffle=True,
                                           pin_memory=True)

In [0]:
question, reply = next(iter(train_loader))

In [83]:
question.shape

torch.Size([100, 25])

In [84]:
reply.shape

torch.Size([100, 27])

create mask

In [85]:
size = 5
torch.ones(size, size)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [87]:
size = 5
torch.triu(torch.ones(size, size))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [88]:
size = 5
torch.triu(torch.ones(size, size)).transpose(0, 1)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [89]:
question[0]

tensor([   2,  255,  406, 4211,   91,  657,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0])

In [90]:
question[0]!=0

tensor([ True,  True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False])

In [0]:
def create_masks(question, reply_input, reply_target):
    """
    sentence:     <start> I slept last night <end>
    reply_input:  <start> I slept last night
    reply_target:         I slept last night <end>
    """

    def subsequence_mask(size):
        mask = torch.triu(torch.ones(size, size)).transpose(0, 1).type(dtype=torch.uint8)
        return mask.unsqueeze(0)

    question_mask = (question!=0).to(device)
    question_mask = question_mask.unsqueeze(1)      # (batch_size, 1, 1, max_words)

    reply_input_mask = reply_input!=0
    reply_input_mask = reply_input_mask.unsqueeze(1)  # (batch_size, 1, max_words)
    reply_input_mask = reply_input_mask & subsequence_mask(reply_input.size(-1)).type_as(reply_input_mask.data)
    # (batch_size, max_words, max_words)
    reply_input_mask = reply_input_mask.unsqueeze(1)  # (batch_size, 1, max_words, max_words)
    reply_target_mask = reply_target!=0               # (batch_size, max_words)

    return question_mask, reply_input_mask, reply_target_mask

### 25.8 Embedding